### ISSUE TITLE
Things Left to Buy

### ISSUE THREAD

**Issue by timmd909** [timmd909/catpoo#8]
Time to start buying the last bit of electronics! Looks like it will be functional after this! 

For the connections, simple is best. With the colored headers, and matching colored cables, how to connect everything will be unambiguous. 

* [x] Screws and nuts
    * [x] 1 × [#1067 - Machine Hex Nut: #4-56 (25-pack)](https://www.pololu.com/product/1067)
    * [x] 6 × [#1068 - Machine Hex Nut: #4-40 (25-pack) ](https://www.pololu.com/product/1068)
    * [x] 1 × [#1966 - Machine Screw: #4-40, 3/4″ Length, Phillips (25-pack)](https://www.pololu.com/product/1966)
    * [x] 4 × [#1963 - Machine Screw: #4-40, 1" Length, Phillips (25-pack)](https://www.pololu.com/product/1963)
    * [x] 4 × [#1962 - Machine Screw: #4-40, 1/2″ Length, Phillips (25-pack)](https://www.pololu.com/product/1962)
    * [x] 4 × [#1966 - Machine Screw: #4-40, 3/4″ Length, Phillips (25-pack)](https://www.pololu.com/product/1966)
* [x] Male headers
    * [x] 2 × [0.100" (2.54 mm) Breakaway Male Header: 1×40-Pin, Straight, Black](https://www.pololu.com/product/965)
    * [x] 2 x [0.100" (2.54 mm) Breakaway Male Header: 1×40-Pin, Straight, Red](https://www.pololu.com/product/2665)
    * [x] 2 × [0.100" (2.54 mm) Breakaway Male Header: 1×40-Pin, Straight, White](https://www.pololu.com/product/2664)
* [x] Pre-Crimped Terminals
    * [x] 2x [Wires with Pre-Crimped Terminals 5-Pack M-F 24" Black](https://www.pololu.com/product/1880)
    * [x] 2x Wires with Pre-Crimped Terminals 5-Pack M-F 24" Red
    * [x] 2x Wires with Pre-Crimped Terminals 5-Pack M-F 24" White
* [x] Crimped Connector Housings
    * [x] 1 × [0.1" (2.54mm) Crimp Connector Housing: 1x1-Pin 25-Pack](https://www.pololu.com/product/1900) (everything else)
    * [x] 1 × 0.1" (2.54mm) Crimp Connector Housing: 1x2-Pin 25-Pack (power only)
    * [x] 1 × 0.1" (2.54mm) Crimp Connector Housing: 1x3-Pin 25-Pack (for sensors)
    * [x] 1 × 0.1" (2.54mm) Crimp Connector Housing: 1x4-Pin 25-Pack (for motor drivers)
* [x] Female headers
    * [x] 2 × 0.100" (2.54 mm) Female Header: 1x20-Pin, Straight (For T Cobbler)
    * [x] 2 × [0.100" (2.54 mm) Female Header: 1x17-Pin, Straight](https://www.pololu.com/product/1111) (for Arduino)
* [ ] Assorted hookup wires
    * [ ] Red 24 gauge stranded wire
    * [ ] White 24 gauge stranded wire
    * [ ] Black 24 gauge stranded wire
* [ ] [Raspberry Pi heatsinks](https://www.amazon.com/Easycargo-Raspberry-Heatsink-Aluminum-conductive/dp/B07217N5LS)

**Comment by timmd909** [comment]
holding off on the heatsinks and wire. Think I have enough...
